#!/usr/bin/env bash
# Install nginx web server

sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
service nginx start
