#!/usr/bin/env bash
# install and configure HAproxy

sudo apt-get -y updates
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get -y install haproxy=2.8.\*

echo "
frontend rattpack.tech
    bind *:80
    default_backend rattpack_backend

backend rattpack_backend
    balance roundrobin
    server 286873-web-01 54.83.66.203:80 check
    server 286873-web-02 100.26.227.228:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo service haproxy start
