#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
hour=0
while [ $hour -le 12 ]; do
	echo "Hour: $hour"
	for i in {1..59}; do
		echo "$i"
	done
	hour=$((hour + 1))
done
