#!/usr/bin/env bash
# install and configure HAproxy

sudo apt-get -y update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y install haproxy=2.8.\*

echo "
frontend rattpack.tech
	bind *:80
	default_backend rattpack_backend

backend rattpack_backend
	balance roundrobin
	server 286873-web-01 54.197.120.203:80 check
	server 286873-web-02 3.94.213.100:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy start
