#!/usr/bin/env bash
#Configure Nginx server to redirect to another page

sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'

echo 'Hello World!' | sudo tee /var/www/html/index.html

NEW_LOCATION="\\\n\n\tlocation = /redirect_me/ {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bakup
sudo sed -i '47i'"$NEW_LOCATION" /etc/nginx/sites-available/default

sudo service nginx restart
