#!/usr/bin/env bash
#

sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

NEW_LOCATION="\\\n\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t\t}\n"
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bakup
sudo sed -i '52i'"$NEW_LOCATION" /etc/nginx/sites-available/default

sudo service nginx restart
